/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroMain: typeof import('./src/components/HeroMain.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PricingSection: typeof import('./src/components/PricingSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesSection: typeof import('./src/components/ServicesSection.vue')['default']
  }
}
