/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import("bootstrap-vue-next")["BButton"]
    BCard: typeof import("bootstrap-vue-next")["BCard"]
    BCardText: typeof import("bootstrap-vue-next")["BCardText"]
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdownDivider: typeof import("bootstrap-vue-next")["BDropdownDivider"]
    BForm: typeof import("bootstrap-vue-next")["BForm"]
    BFormInput: typeof import("bootstrap-vue-next")["BFormInput"]
    BFormSelect: typeof import("bootstrap-vue-next")["BFormSelect"]
    BImg: typeof import("bootstrap-vue-next")["BImg"]
    BInputGroup: typeof import("bootstrap-vue-next")["BInputGroup"]
    BInputGroupAppend: typeof import("bootstrap-vue-next")["BInputGroupAppend"]
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BOffcanvas: typeof import("bootstrap-vue-next")["BOffcanvas"]
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTab: typeof import("bootstrap-vue-next")["BTab"]
    BTabs: typeof import("bootstrap-vue-next")["BTabs"]
    BToastOrchestrator: typeof import("bootstrap-vue-next")["BToastOrchestrator"]
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroMain: typeof import('./src/components/HeroMain.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PricingSection: typeof import('./src/components/PricingSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesSection: typeof import('./src/components/ServicesSection.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
